services:
  # Static Site Service
  - type: web
    name: mr-market-static
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: static
    rootDir: interface

  # Background Worker Service
  - type: web
    name: mr-market-worker
    env: node
    buildCommand: npm install
    startCommand: npm start
    rootDir: server

databases:
  - name: mr-market-db
    databaseName: mrmarket
    region: oregon

