import { Controller, Get, Post, Delete, Body, Param, UseGuards } from '@nestjs/common';
import { ApiOperation, ApiResponse, ApiTags } from '@nestjs/swagger';
import { JwtAuthGuard } from 'src/modules/auth/jwt-auth.guard';
import { ExchangeService } from 'src/modules/mixin/exchange/exchange.service';
import { AddAPIKeyDto } from './exchanges.dto';

@ApiTags('Admin/Exchanges')
@Controller('admin/exchanges')
@UseGuards(JwtAuthGuard)
export class AdminExchangesController {
  constructor(private readonly exchangeService: ExchangeService) { }

  @Get('/keys')
  @ApiOperation({ summary: 'Get all API keys' })
  @ApiResponse({ status: 200, description: 'Return all API keys' })
  async getAllAPIKeys() {
    return await this.exchangeService.readAllAPIKeys();
  }

  @Post('/keys')
  @ApiOperation({ summary: 'Add a new API key' })
  @ApiResponse({ status: 200, description: 'API key added successfully' })
  async addAPIKey(@Body() data: AddAPIKeyDto) {
    const keyData = {
      ...data,
      exchange_index: data.exchange_index || Date.now().toString(),
    };
    // We cast to any here because key_id is generated by the database/entity
    return await this.exchangeService.addApiKey(keyData as any);
  }

  @Get('/key-pair')
  @ApiOperation({ summary: 'Get encryption public key' })
  @ApiResponse({ status: 200, description: 'Return encryption public key' })
  async getEncryptionPublicKey() {
    return this.exchangeService.getEncryptionPublicKey();
  }

  @Delete('/keys/:key_id')
  @ApiOperation({ summary: 'Remove an API key' })
  @ApiResponse({ status: 200, description: 'API key removed successfully' })
  async removeAPIKey(@Param('key_id') key_id: string) {
    return await this.exchangeService.removeAPIKey(key_id);
  }
}
